#!/bin/bash

# !! IMPORTANT !! INCREASE THE LIMIT OF TASKS IN /etc/systemd/system.conf
echo "# Distrotunnel install script - Increase the limit of tasks" \
    | sudo tee -a /etc/systemd/system.conf
echo "DefaultTasksMax=8706" \
    | sudo tee -a /etc/systemd/system.conf

# Install rust
curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y

# Add rust to path
echo 'export PATH="$HOME/.cargo/bin:$PATH"' >> ~/.zshrc
source ~/.zshrc

# install dmt
git submodule update --init --recursive --remote $DISTROTUNNEL/scripts/dmt
cargo build --manifest-path $DISTROTUNNEL/scripts/dmt/Cargo.toml --release

# Install atuin
cargo install atuin

# install AUR/pacman packages
$DISTROTUNNEL/scripts/dmt/target/release/main -i \
        bat \
        bash-completion \
        chezmoi \
        curl \
        dust \
        exa \
        fd \
        flameshot \
        fzf \
        gitflow-avh \
        github-cli \
        htop \
        neofetch \
        neovim \
        openssh \
        pulseaudio \
        ripgrep \
        starship \
        taskwarrior-tui \
        timew \
        vivaldi \
        tmux \
        tmuxp \
        xclip \
        yarn \
        ; sudo pacman -Rns $(pacman -Qtdq) \
        ; sudo pacman -Scc --noconfirm \
        ; sudo rm -Rf /var/cache/pacman/pkg/*.

# install zsh-syntax-highlighting
mkdir -p ~/.zsh
git clone https://github.com/zsh-users/zsh-syntax-highlighting.git ~/.zsh/zsh-syntax-highlighting

# Uncomment the following line if your .zshrc not already have it
# echo "source ~/.zsh/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh" >> ~/.zshrc

# install gh autocomplete
gh completion -s zsh > ~/.zsh/_gh

# export some packages then cannot have been installed via dmt
yay -Ql sudo | grep /usr/bin/ | tail -n +2 | awk '{print $2}' | while read path; do
    distrobox-export -b $path -ep $DISTROTUNNEL/bin;
done

yay -Ql git | grep /usr/bin/ | tail -n +2 | awk '{print $2}' | while read path; do
    distrobox-export -b $path -ep $DISTROTUNNEL/bin;
done

# Change the name of the dmt binary
mv $DISTROTUNNEL/scripts/dmt/target/release/main $DISTROTUNNEL/scripts/dmt/target/release/dmt

distrobox-export -b $DISTROTUNNEL/scripts/dmt/target/release/dmt -ep $DISTROTUNNEL/bin
distrobox-export -b $DISTROTUNNEL/scripts/won -ep $DISTROTUNNEL/bin 
