#!/bin/bash
# dmt is an acronym for distrotunnel management tool

noconfirm=""
if [[ "$1" == "--noconfirm" ]]; then
    noconfirm="--noconfirm"
    shift
fi

case "$1" in
    -a)
        shift
        for pkg in "$@"; do
            if yay -S $noconfirm $pkg; then
                yay -Ql $pkg | grep /usr/bin/ | tail -n +2 | awk '{print $2}' | while read path; do
                if distrobox-export -b $path -ep $DISTROTUNNEL/bin; then
                    execname=$(basename $path)
                    distrobox-export --app $execname > /dev/null 2>&1;
                fi
            done
                echo "Package $pkg installed and exported successfully."
            else
                echo "Error installing package $pkg."
            fi
        done
        ;;
    -r)
        shift
        for pkg in "$@"; do
            yay -Ql $pkg | grep /usr/bin/ | tail -n +2 | awk '{print $2}' | while read path; do
            execname=$(basename $path)
            distrobox-export --app $execname --delete;
            rm -rf $DISTROTUNNEL/bin/$execname
        done
            if yay -R $noconfirm $pkg; then
                echo "Package $pkg uninstalled successfully."
            else
                echo "Error uninstalling package $pkg."
            fi
        done
        ;;
    -u)
        if yay -Syu $noconfirm; then
            echo "Packages updated successfully."
        fi
        ;;
    -h)
        echo "cmt is an acronym for container management tool"
        echo "Usage:"
        echo "--noconfirm... # Avoid interactions with user"
        echo "-a <package>... # Add packages"
        echo "-r <package>... # Remove packages"
        echo "-u # Update packages"
        echo "-h # Show help"
        ;;
    *)
        echo "Invalid option, run cmt -h for help."
        ;;
esac
