#!/bin/bash

rm -rf ~/.local/share/applications/distrotunnel-*.desktop
rm -rf $DISTROTUNNEL/bin
distrobox-rm distrotunnel --force
podman image rm localhost/distrotunnel:latest
echo "Distrotunnel uninstalled!"
