#!/bin/bash
# won is an acronym for "work on"

if [[ $# -eq 1 ]]; then
    selected=$1
else
    selected=$(find ~/projects -mindepth 1 -maxdepth 2 -type d -not -path "*/.*" | fzf)
fi

if [[ -z $selected ]]; then
    exit 0
fi

nvim "$selected"
